image: gitpod/workspace-full-vnc

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser

tasks:
  - name: gtoolkit
    init: ./get-gtoolkit.sh
    command: sudo sed -i s/1920x1080/$SCREENSIZE/ /usr/bin/start-vnc-session.sh && sudo killall Xvfb && source ~/.bashrc && ./run-gtoolkit.sh
